Tracker:AddLocations("locations/0 Overworld.json")
Tracker:AddLocations("locations/1-1 Valley of Fire.json")
Tracker:AddLocations("locations/1-2 Dagger Peak.json")
Tracker:AddLocations("locations/1-3 Cliffs of Desolation.json")
Tracker:AddLocations("locations/1-4 Lost Cave.json")
Tracker:AddLocations("locations/1-5 Volcanic Cavern.json")
Tracker:AddLocations("locations/1-6 Dragon's Lair.json")
Tracker:AddLocations("locations/2-1 Castle Courtyard.json")
Tracker:AddLocations("locations/2-2 Dungeon of Torment.json")
Tracker:AddLocations("locations/2-3 Tower Armory.json")
Tracker:AddLocations("locations/2-4 Castle Treasury.json")
Tracker:AddLocations("locations/2-5 Chimera's Keep.json")
Tracker:AddLocations("locations/3-1 Poisoned Fields.json")
Tracker:AddLocations("locations/3-2 Haunted Cemetery.json")
Tracker:AddLocations("locations/3-3 Venemous Spire.json")
Tracker:AddLocations("locations/3-4 Toxic Air Ship.json")
Tracker:AddLocations("locations/3-5 Vat of the Plague Fiend.json")
Tracker:AddLocations("locations/4-1 Arctic Docks.json")
Tracker:AddLocations("locations/4-2 Frozen Camp.json")
Tracker:AddLocations("locations/4-3 Crystal Mine.json")
Tracker:AddLocations("locations/4-4 Erupting Fissure.json")
Tracker:AddLocations("locations/4-5 Yeti's Cavern.json")
Tracker:AddLocations("locations/5 Desecrated Temple.json")
Tracker:AddLocations("locations/5 Altar of Skorne.json")
Tracker:AddLocations("locations/6-1 Battle Trenches.json")
Tracker:AddLocations("locations/6-2 Fortified Towers.json")
Tracker:AddLocations("locations/6-3 Infernal Fortress.json")
Tracker:AddLocations("locations/7 Gates of the Underworld.json")
